### ISSUE TITLE
New aoe2 de recorded files parsing ending early

### ISSUE THREAD

**Issue by arunpatala** [happyleavesaoc/aoc-mgz#24]
Hi,

First of all want to thank for for this great work.

I was trying to parse files in aoe2 de recorded files of the past few days.  The parsing is ending early with the last operation being embedded with default consuming the rest of the file (from my understanding). Maybe they added new embedded operation which is not handled right now. I would like to help in anyway. 

Again thanks.

**Comment by arunpatala** [comment]
Container: 
    type = embedded (total 8)
    start = 177568
    op = 2392
    marker = 2
    subtype = default (total 7)
    end = 2780254

**Comment by happyleavesaoc** [comment]
Thanks for the report. There's probably a change to an existing action that we're not accounting for.

**Comment by arunpatala** [comment]
Hi,

The parsing works all right in the fast mode. just fyi.

Thanks

**Comment by MLeadbetter** [comment]
Just to add to this, rather than just new recs, it doesn't seem to have worked correctly for a while. I checked a AoE2 DE rec from July and saw the same behavior. Though more events are processed before the "embedded" container. It managed to do 37128 events, compared to the fast mode which parsed 159697 events. I also tried it on some recs from June. Unfortunately the code errors out for these while trying to parse them.

**Comment by rioderaca** [comment]
Great work indeed.

Am wondering, before starting to go deeper into the code, if this parser still works with the latest game version (101.101.43210.0 5867313).

Currently am getting this error:

`RuntimeError: invalid mgz file: expected b'\xa3_\x02\x00' but parsed b'\x00\x00\x00\x00`
`(parsing) -> de -> de`

**Comment by happyleavesaoc** [comment]
It should work on ranked multiplayer recorded games. Any other type may or may not be supported - it depends.

**Comment by rioderaca** [comment]
Nevermind, that error came while using the pip installed version, works with the code in this repo now.
